export const ActionType = {
  ON_FAILURE: "FETCH_EXAMPLE_FAILURE",
  ON_SUCCESS: "FETCH_EXAMPLE_SUCCESS",
  ON_REQUEST: "FETCH_EXAMPLE_REQUEST",

  ON_FAILURE_COMMON_API: "FETCH_COMMON_API_FAILURE",
  ON_SUCCESS_COMMON_API: "FETCH_COMMON_API_SUCCESS",
  ON_REQUEST_COMMON_API: "FETCH_COMMON_API_REQUEST",
};
