export const ActionType = {
  ON_FAILURE: "FETCH_EXAMPLE_FAILURE",
  ON_SUCCESS: "FETCH_EXAMPLE_SUCCESS",
  ON_REQUEST: "FETCH_EXAMPLE_REQUEST",

  ON_FAILURE_COMMON_API: "FETCH_COMMON_API_FAILURE",
  ON_SUCCESS_COMMON_API: "FETCH_COMMON_API_SUCCESS",
  ON_REQUEST_COMMON_API: "FETCH_COMMON_API_REQUEST",

  ON_LOCATION_SET: "ON_LOCATION_SET",
  ON_FAILURE_LOCATION_API: "FETCH_LOCATION_API_FAILURE",
  ON_SUCCESS_LOCATION_API: "FETCH_LOCATION_API_SUCCESS",
  ON_REQUEST_LOCATION_API: "FETCH_LOCATION_API_REQUEST",

  ON_CATEGORY_SET: "ON_CATEGORY_SET",
  ON_FAILURE_CATEGORY_API: "FETCH_CATEGORY_API_FAILURE",
  ON_SUCCESS_CATEGORY_API: "FETCH_CATEGORY_API_SUCCESS",
  ON_REQUEST_CATEGORY_API: "FETCH_CATEGORY_API_REQUEST",

  ON_SERVICE_LIST_SET: "ON_SERVICE_LIST_SET",
  ON_FAILURE_SERVICE_LIST_API: "FETCH_SERVICE_LIST_API_FAILURE",
  ON_SUCCESS_SERVICE_LIST_API: "FETCH_SERVICE_LIST_API_SUCCESS",
  ON_REQUEST_SERVICE_LIST_API: "FETCH_SERVICE_LIST_API_REQUEST",
};
